# Generated by Django 4.2.6 on 2023-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_playlistitem_item_type_playlist_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='items',
            new_name='music',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='album'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='artista'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='music',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='titulo'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='music_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='id'),
        ),
    ]
