# Generated by Django 4.2.6 on 2023-10-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playlistitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
    ]
