# Generated by Django 4.2.6 on 2023-10-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_playlist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.playlist'),
        ),
    ]
