# Generated by Django 4.2.6 on 2023-10-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playlistitem_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.playlist'),
        ),
    ]
