# Generated by Django 4.2.6 on 2023-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_playlistitem_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='playlist_item', to='core.playlistitem'),
        ),
    ]
