# Generated by Django 4.2.6 on 2023-10-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_playlistitem_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.playlist'),
        ),
    ]
