# Generated by Django 4.2.6 on 2023-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_playlistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='playlist_items', to='core.playlistitem'),
        ),
    ]
