# Generated by Django 4.2.6 on 2023-10-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_addition_album_artist_fan_friend_listener_song_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
