# Generated by Django 4.2.6 on 2023-10-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_playlist_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='Playlists',
        ),
    ]
