# Generated by Django 4.2.6 on 2023-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_playlist_playlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
    ]
