# Generated by Django 4.2.6 on 2023-10-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_rename_title_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='follower',
        ),
        migrations.AlterField(
            model_name='listener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
